# OpenAI Homebrew Tools

Homebrew tap for OpenAI command-line tools.

## OpenAI CLI

This tap publishes the `openai` cask for the OpenAI CLI once public release artifacts are available.

```sh
brew install openai/tools/openai
```

The cask definition is generated by the OpenAI CLI release workflow.

## Tart-related projects

[Tart](https://github.com/openai/tart)-related projects publish the following formulas:

```sh
brew install openai/tools/tart
brew install openai/tools/softnet
brew install openai/tools/orchard
brew install openai/tools/tart-guest-agent
```

## License

Copyright 2026 OpenAI

This repository is licensed under the Apache License 2.0. See [LICENSE](LICENSE).
